---

# Attributes
- include: attributes/{{ item['task'] }}.yml
  with_manala_files_attributes:
    - "{{ manala_files_attributes }}"
    - "{{ manala_files_attributes_defaults }}"
  tags:
    - manala_files
