---

- name: vars > Variables
  set_fact:
    __item: "{{
      ((__manala_files_attributes_results|default({'ansible_facts':{'__item':{}}})).ansible_facts.__item)|combine(
        {
          item.src: item|combine({
            'path':      item.src,
            'src':       None,
            'state':     'directory',
            'task_file': true
          }),
          item.path: item|combine({
            'state':     'link',
            'task_file': true
          })
        }
          if (item.has_key('state') and (item.state == 'link_directory')) else
        {
          item.path: item|combine(
            {'task_template': true}
              if (item.has_key('template')) else
            {'task_content': true}
              if (item.has_key('content')) else
            {'task_copy': true}
              if (item.has_key('copy')) else
            {'task_url': true}
              if (item.has_key('url')) else
            {'task_file': true}
          )
        }
      )
    }}"
  with_items: "{{ manala_files_attributes }}"
  register: __manala_files_attributes_results
