---

- name: attributes/content
  tags:
    - manala_files
  block:

    - name: attributes/content > Copy "{{ item.path }}"
      copy:
        dest:    "{{ item.path }}"
        content: "{{ item.content }}"
        force:   "{{ item.force|default(omit) }}"
        owner:   "{{ item.user|default(omit) }}"
        group:   "{{ item.group|default(omit) }}"
        mode:    "{{ item.mode|default(omit) }}"
