---

- tags:
    - manala_files
  block:

    - name: attributes/link_file > Force file stat "{{ item.src }}"
      stat:
        path: "{{ item.src }}"
        follow: true
      register: __file
      when: item.file.force
      check_mode: false

    - name: attributes/link_file > Force file clean "{{ item.src }}"
      file:
        path: "{{ item.src }}"
        state: absent
      when: item.file.force
            and (__file.stat.exists)
            and (not __file.stat.isreg)

    - name: attributes/link_file > File parents "{{ item.src|dirname }}"
      file:
        path: "{{ item.src|dirname }}"
        state: directory
        owner: "{{ item.file.user|default(omit) }}"
        group: "{{ item.file.group|default(omit) }}"
        mode: "{{ item.file.mode|default(omit) }}"
      when: item.file.parents

    - name: attributes/link_file > Create file "{{ item.src }}"
      copy:
        dest: "{{ item.src }}"
        content: ""
        force: false
        owner: "{{ item.file.user|default(omit) }}"
        group: "{{ item.file.group|default(omit) }}"
        mode: "{{ item.file.mode|default(omit) }}"

    - name: attributes/link_file > File "{{ item.src }}"
      file:
        path: "{{ item.src }}"
        state: file
        owner: "{{ item.file.user|default(omit) }}"
        group: "{{ item.file.group|default(omit) }}"
        mode: "{{ item.file.mode|default(omit) }}"

    - name: attributes/link_file > Link parents "{{ item.path|dirname }}"
      file:
        path: "{{ item.path|dirname }}"
        state: directory
        owner: "{{ item.link.user|default(omit) }}"
        group: "{{ item.link.group|default(omit) }}"
        mode: "{{ item.link.mode|default(omit) }}"
      when: item.link.parents

    - name: attributes/link_file > Force link stat "{{ item.path }}"
      stat:
        path: "{{ item.path }}"
      register: __link
      when: item.link.force
      check_mode: false

    - name: attributes/link_file > Force link clean "{{ item.path }}"
      file:
        path: "{{ item.path }}"
        state: absent
      when: item.link.force
            and (__link.stat.exists)
            and (not __link.stat.islnk)

    - name: attributes/link_file > Link "{{ item.path }}"
      file:
        path: "{{ item.path }}"
        state: link
        src: "{{ item.src }}"
        owner: "{{ item.link.user|default(omit) }}"
        group: "{{ item.link.group|default(omit) }}"
